// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbgjOexWf5Kx6oYwJxkx4JaVnn2zB56dM',
    appId: '1:639295351233:web:7b2cfa33bbffb1e23ce740',
    messagingSenderId: '639295351233',
    projectId: 'notilistapplication',
    authDomain: 'notilistapplication.firebaseapp.com',
    storageBucket: 'notilistapplication.appspot.com',
    measurementId: 'G-GLEJ48XB9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8-MLMd4Ydu0uN-mH9ATdeCxm0e4pT9hw',
    appId: '1:639295351233:android:a529fbf0b23809453ce740',
    messagingSenderId: '639295351233',
    projectId: 'notilistapplication',
    storageBucket: 'notilistapplication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9jD-r-paa8VnEENha0zhS85Otvzgu3t8',
    appId: '1:639295351233:ios:8fc0e7398914b10a3ce740',
    messagingSenderId: '639295351233',
    projectId: 'notilistapplication',
    storageBucket: 'notilistapplication.appspot.com',
    iosBundleId: 'com.example.notilist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9jD-r-paa8VnEENha0zhS85Otvzgu3t8',
    appId: '1:639295351233:ios:8fc0e7398914b10a3ce740',
    messagingSenderId: '639295351233',
    projectId: 'notilistapplication',
    storageBucket: 'notilistapplication.appspot.com',
    iosBundleId: 'com.example.notilist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbgjOexWf5Kx6oYwJxkx4JaVnn2zB56dM',
    appId: '1:639295351233:web:6f50a0190a0353433ce740',
    messagingSenderId: '639295351233',
    projectId: 'notilistapplication',
    authDomain: 'notilistapplication.firebaseapp.com',
    storageBucket: 'notilistapplication.appspot.com',
    measurementId: 'G-PSYCZHH429',
  );
}
